language: node_js
node_js:
  - "8"
before_script:
  - bower install
script:
  - npm run test
  - npm run build

deploy:
  skip_cleanup: true
  provider: surge
  project: build/es6-bundled/
  domain: minecraft.gavinmogan.com
  on: master
